---
- name: copy files from local to remote
  hosts: app
  tasks:
    - name: Create dir
      file:
        path: /tmp/dir
        state: directory

    - name: filecopy
      copy:
        src: /tmp/file
        dest: /tmp/dir  

