---
- name: multiple plays
  hosts: appdb
  become: true
  become_user: root
  become_method: su
  tasks:
  - name: install firewall package
    yum:
      name:
        - httpd
        - firewalld
      state: latest
    delegate_to: ansible2.example.com

  - name: start services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - httpd
      - firewalld

  - name: input from include file
    import_tasks: firewall.yml
