---
- name: multiple plays
  hosts: app
  gather_facts: false
  user: ansiuser
  become: true
  tasks:
  - name: install firewall package
    yum:
      name:
        - httpd
        - firewalld
      state: latest

  - name: start services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - httpd
      - firewalld

  - name: input from include file
    include: firewall.yml
