---
  - name: Deploy web application
    hosts: db_and_web_server1, db_and_web_server2
    become: true
    become_user: root
    become_method: sudo
  
    tasks:
      - name: Install Python and its dependencies
        yum:
          name:
            - python3
            - python3-setuptools
            - python3-devel
            - python3-pip
            - python3-PyMySQL
          state: installed
      - include: tasks/deploy_db.yml
      - include: tasks/deploy_web.yml

