---
- name: simple boolean task
  hosts: webserver
  gather_facts: yes
  vars:
    supported_distros:
      - RedHat
      - Fedora
  tasks:
    - name: Httpd pks install where supported
      yum:
        name: httpd
        state: present
      when: >
          ( ansible_distribution == "RedHat" and ansible_distribution_major_version == "7" )
          or
          ( ansible_distribution == "Fedora" and ansible_distribution_major_version == "28" )