---
- name: Print Ansible Facts
  hosts: db
  tasks:
    - name: Print all facts
      debug:
        msg: >
              The package to install on {{ ansible_facts['fqdn'] }} is {{ ansible_facts['ansible_local']['custom']['packages']['web_pkg'] }}
