- name: registered variable usage as a loop list
  hosts: app
  gather_facts: yes
  tasks:

  - name: get device name
    set_fact:
      device_name: "{{ item.key }}"
    with_dict: "{{ ansible_devices }}"
    when: "item.value.host.startswith('Non')"

  - name: show all values for selected device name
    debug: var=ansible_devices[device_name]

  - name: show only device name
    debug: var=device_name

    

    
    
    
    
    
    

    
    

    
    
    