- name: Install MySQL database
  yum:
    name:
      - mysql-server
      - mysql
    state: installed
- name: Install python flask dependency
  pip:
    name:
      - flask
      - flask-mysql
    state: present
- name: Start the database service
  service:
    name: mysqld
    state: started
    enabled: yes
- name: Create MySQL Database
  mysql_db:
    name: "{{ mysql_db }}"
    state: present

- name: Create database and database users
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_pass }}"
    priv: '*.*:ALL,GRANT'
    state: present
    host: '%'
